### ISSUE TITLE
Create Basic Team Model and Views

### ISSUE THREAD

**Issue by Bennm23** [Bennm23/f5new#2]
### Description ### 

I need to create the initial Team Model and rudimentary Team Views so that I can provide the team framework.

### Requirements ### 

- [x] The Team Model is created and is integrated with the database
- [x] A list teams view is created
- [x] A detail team view is created
- [x] A create team view is created, only registered users may create teams

**Comment by reyesjl** [comment]
Closing this issue for completion.
