### ISSUE TITLE
Create Basic User Model and Views

### ISSUE THREAD

**Issue by Bennm23** [Bennm23/f5new#3]
### Description ### 

I need to create the initial User Model and rudimentary User Views so that I can provide the user framework.

### Requirements ### 

- [x] The User Model is created and is integrated with the database
- [x] A create user view is created
- [x] A login user view is created
- [x] Upon login, a user session is established

**Comment by reyesjl** [comment]
Started work: 

Created model and create user together. 

We have decided to do authentication first, then integrate authorization later with pages. 

To be continued..

**Comment by reyesjl** [comment]
@Bennm23 looks good now! Logged in and works fine too. Closing this issue.
