### ISSUE TITLE
Add Maintainers for Teams

### ISSUE THREAD

**Issue by Bennm23** [Bennm23/f5new#35]
# Description 

Coaches/Team Admins need the ability to manage the team. 

# Requirements 
- [ ] The team creator is made a team maintainer at creation
- [ ] Team maintainers are able to add other maintainers
- [ ] Team maintainers are able to approve users requests to join the team
- [ ] Team maintainers are able to remove members

**Comment by reyesjl** [comment]
1. As a player / requesting user, I can submit a request to join a team. 
2. As a player, I can see the status of your request in my dashboard panel.
3. As a team maintainer I must be able to see my teams requests. I can 'approve' or 'deny' them and see their information.
4. As a player if a request has been denied, it will be removed from your list of team requests. 
5. As a player if the request is approved, you will have that team listed under your teams in dashboard.
6. As a user of the site, when visitant this users profile, I will be able to see their team alliance. 

**_Can you join more than one team?_** @Bennm23
