### ISSUE TITLE
Add login session timeout so users don't stay logged in indefinitely

### ISSUE THREAD

**Issue by Bennm23** [Bennm23/f5new#37]
### Description ###

I need to log out users after X minutes of use so that login sessions are not indefinite

### Requirements ###

- [ ] User Session is ended after X minutes of login

**Comment by reyesjl** [comment]
created branch and pulled for dev

**Comment by reyesjl** [comment]
updated time zone to America/New_York (aka EST time)

**Comment by reyesjl** [comment]
add session expire for user session / cookie

note: 1800 is = 30min 
after 30 mins of inactivity, the user session will expire
if the user send a request to the server for any reason, for example requesting a page, using filter search, etc - the expire timer will be reset for 30mins. 

There is a setting for loggin the user out on browser close, but I assume it could be bad incase user exits by accident, and i they forget to log out, they will be logged out in 30 mins. Not sure if this is secure enough, i think its okay.
