### ISSUE TITLE
Allow users to register as a user type

### ISSUE THREAD

**Issue by Bennm23** [Bennm23/f5new#6]
### Description ###

I need to allow users to register as a Coach, Player or Other on signup so I can distinguish accounts.

### Requirements ###

- [x] On Signup, users can register as a Coach, Player or Other
- [x] User Type is stored on the User model

**Comment by reyesjl** [comment]
@Bennm23 do we want to verify these somehow?

**Comment by reyesjl** [comment]
Created branch and pulled for dev.
