### ISSUE TITLE
Add email verification to user signup

### ISSUE THREAD

**Issue by Bennm23** [Bennm23/f5new#8]
### Description ###

I need to add email verification to user signup so that I can ensure users are valid.

### Requirements ###

- [x] Add email field to user signup form
- [x] On signup, user will be sent a verification email
- [x] On user verification, they are granted 'verified' status
- [x] Until the user is validated, they shall be 'unverified'

**Comment by reyesjl** [comment]
- Created branch and pulled for development.

**Comment by reyesjl** [comment]
- Moved USER_TYPES LIST to constants.py

**Comment by reyesjl** [comment]
<img width="455" alt="email1" src="https://github.com/Bennm23/f5new/assets/37513330/582ec5a5-2ec6-4874-9138-f26a22e61729">
<img width="374" alt="email2" src="https://github.com/Bennm23/f5new/assets/37513330/e0d5fda8-d6c9-42cb-9a18-482665272438">

**Comment by reyesjl** [comment]
- need to add route user will click in their email.
- build reverse() route using user + verify code, will activate the user in our system.
- need to add something that will not allow the user to login if their account is unverified.

**Comment by reyesjl** [comment]
## Updated :)
<img width="560" alt="email1" src="https://github.com/Bennm23/f5new/assets/37513330/0508d415-3836-4a53-9a16-5701efcd0fbe">
<img width="362" alt="Screenshot 2023-11-28 130031" src="https://github.com/Bennm23/f5new/assets/37513330/9f597166-0cfd-40eb-86bc-7d8e0db30a13">
