### ISSUE TITLE
Add Blog Search Functionality

### ISSUE THREAD

**Issue by Bennm23** [Bennm23/f5new#9]
### Description ###

I need to give users the ability to search through the current blogs.

### Requirements ###

- [ ] Blogs can be searched by string
- [ ] Blogs can be filtered by [ 'Author Type', ...]
- [ ] Only blogs that meet the search and filter are shown
- [ ] The search results shall update on search text change and filter change, not just on submit **Confirm**

**Comment by reyesjl** [comment]
Created branch and pulled for development.
